### ISSUE TITLE
Profile R code

### ISSUE THREAD

**Issue by YannLadner** [CorrelAidSwitzerland/a4d#24]
One could use the `Profvis` package (https://rstudio.github.io/profvis/index.html) to observe the performance of the code.

**Comment by pmayd** [comment]
I just continued with `profvis`, one of the best packages I have ever used, beatifully aggregated results. Anyway, I found a major "problem" in our first script, basically `readxl::read_excel` which was not using the `col_types` parameter, thus opening every sheet and guessing the col type for all columns! But we don't need this, because the first script is extracting the data as is so everything remains character. A simple `col_types ="c"` changed this and we get a tremendous performance boost.

**Comment by pmayd** [comment]
Ok I have to say the runtime was just much faster with the foreach approach so it is really sad that we lost this and are back to a serial code that runs only file by file...but I hope this at least makes it easier between different OS and also for us to develop without needing to source every change or new file. However, I hope we can still improve performance somehow. I only looked at script 1 with profvis so we can still continue inspecting the other files
