### ISSUE TITLE
Look into Looker Studio and understand options and UI

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#64]
We need a good understanding of Looker Studio, its UI and functionality, to be able to deliver the dashboards, graphs, tables and reports that A4D wants. So we should invest some time understanding all features Looker Studio is offering

output should be a demo report with example visualizations showing the possibilities and kind of questions that we can answer with Looker Studio

**Comment by lboel** [comment]
Check "Blended Data Source" consequences to existing report pages (Reason: "Renaming or Changing Filters/ Blending Data breaks existing diagrams..., not really sure what happend to https://lookerstudio.google.com/u/0/reporting/a972f166-49c2-455b-a2b5-87f5ef04eea9/page/p_zd7ofzf99c/edit)

We need to find some good way to inform all report devs (in the same report) what changed in the background because Looker have'nt really a good feature to do this.
