### ISSUE TITLE
Create a close-enough reimplementation of the 2023 CSP Quota Overview

### ISSUE THREAD

**Issue by pmayd** [CorrelAidSwitzerland/a4d#83]
Please have a look at the quota overview in the file 2023 CSP Quota Overview.xlsx and try to reimplement this kind of report in Looker Studio

Start with Country overview and keep the monthly overview for later

You can find the documents in the tyla bucket.

**Comment by pmayd** [comment]
I send an email to Tyla with a lot of questions

**Comment by lboel** [comment]
perfect, can you add the mail here (or the questions). got only little time since Wednesday (kid got sick, will be in the kindergarden again tomorrow) but have played around a little bit with Looker.

**Comment by pmayd** [comment]
Good point, basically I asked about every column haha

> Hi Tyla,
>
> hope, you are doing well! 
>
> Here are my current questions about the quota overview, feel free to answer them here or in our next meeting. I am only > asking about the first sheet for now:

> 1. Where is "Clinic Start Date" (column F) coming from? Do we already have this information or do we have to add this information to the database?
> 2. Where is "Total Enrolled" (column G) coming from? Is this the current number of patients? If so, only active patients? > So can we get this number from counting all active patients for this clinic in the last month? It seems that is not the case > as for the first clinic the monthly sheet tells us that there are only 26 patients, not 35. Maybe this is the number of all patients since the beginning? 
> 3. Where is "Total Transfer IN" (column H) coming from? Do we already have this information or do we have to add this information to the database?
> 4. Where is "Total T1D Lost*" (column I) coming from? Is this calculated by counting the number of patients that have died? If so, is this for the whole period/year or since the beginning?
> 5. Where is "Monitoring ONLY" (column J) coming from? Do we already have this information or do we have to add this information to the database?
> 6. Where is "A4D Support" (column K) coming from? It seems like this is the number of the last month? Ah it is not, see next question, so how is this different from the next column?
> 7. Where is "Total Active T1D YTD" (column L) coming from? It seems like this is the number of the last month? What does YTD mean?
> 8. I guess we have to ignore column "Aug 2023" as we don't have current tracker files?
> 9. Where is "Patient Quota 2023" coming from? Given that we have only data for 2022 is this relevant, do we want to calculate this? How is this number calculated?
> 10. What are the numbers in the columns R-W? Patient numbers? But which one? So basically an aggregation over all clinics in a given country? Seems like this is "Total Active" from column L?
> 
> I originally thought that the quota overview sheet 1 was an annual overview, for the current year, but it seems this is an overview of the clinics since the beginning, right? So all the numbers are basically over the whole time of the cooperation...so we can aggregate all clinic information since the beginning (for sheet 1)
> 
> I think we can relatively easily recreate the annual table in columns Q-AB without data for 2023. So should we do this for the end of 2022 instead? Same question applies to the main Table in columns B-O: should we try to display such a table for all the clinics from beginning until end of 2022?

**Comment by pmayd** [comment]
I started with a Query to determine the number of active patients per clinic: https://console.cloud.google.com/bigquery?sq=852079378749:afedad09c9054e8bbd67d05f1a182327

Question is how we can best put this into Looker Studio, something I want to discuss with @lboel. I think it is not so important if this information is long or wide but at the moment A4D always has wide format, so the time axis is horizontally in their excel files, I think in SQL it is only possible to have it on the vertical? Anyhow, I can create a table this way but I am not sure how we can fetch the table in Looker Studio. I guess long is easy enough as we have fixed dimensions: clinic_code, year, month and the number so you can directly select these 4. But if we do it horizontally, each month will become a dimension...

**Comment by pmayd** [comment]
new links:
https://console.cloud.google.com/bigquery?sq=852079378749:4a939578e9574b6a86317525d435433b
https://console.cloud.google.com/bigquery?sq=852079378749:0fc43769cd5e423eabf70580762e9fb4

**Comment by pmayd** [comment]
I played around with SQL more and it seems in fact there are no limits to what you can do...I am a data engineer and it is a little bit sad that I did not know this but I am learning ;)

So basically with `PIVOT` we can achieve the exact same format as in the excel file, basically switching to a wide format. Even if we have to hard code the numbers I think this is fine as this will not change often and it is easy enough to change and maintain. I have updated the saved query to show the pivot table approach

**Comment by tasosbada** [comment]
@pmayd I see that now the patient_data view work properly! When I tried to select there were an error of duplicate id, but now it work properly. It seems that JOIN with USING works better when the join keys are identical. Thanks!!!

I also packed the creation of a similar view in a query that generate it just to have it as example. 

![image](https://github.com/CorrelAidSwitzerland/a4d/assets/15861245/f4068ec8-7293-4c33-9f8f-f01fc62a15e4)

**Comment by pmayd** [comment]
Yes Luke and I were investigating this issue yesterday, I have no idea why this works but Luke found that tip to use Using here. 

Yeah I had used create view before but if we do it this way you cannot change the query behind it under details, only view the query. The nice thing about the current solution is that you can change the query afterwards.

Now everything works really well!

**Comment by tasosbada** [comment]
Very nice! Thanks Luke too!

You are right we can not change the materialized but the normal views yes. 

Do we have a specific table that view that we want to create? In the evening I have time. I see that almost all of the table in 2023 CSP Quota Overview are done.

**Comment by pmayd** [comment]
Yea exactly we want to rebuild the quota dashboards and we did pair programming together yesterday and now it's only about details. I have to check what Luke did manage to finish yesterday but in the end it would be nice to have the sheets available.

I will send You in Slack the link to the report

**Comment by lboel** [comment]
Update:

So after a longer session with Michael in Pair Programming Style we have a fairly far version of the Quota Excel ready in Looker Studio.

Only three clinic code seem to be not correctly calculated (if we use Tylas` Quota Sheet of  2022 as ground truth):
![image](https://github.com/CorrelAidSwitzerland/a4d/assets/8046474/1addf7ec-a729-4645-89b0-f86fd6a7314b)

This would be the Overview Table and the Diagram:
![image](https://github.com/CorrelAidSwitzerland/a4d/assets/8046474/90915db5-3b59-4bd0-9616-e835511a380e)


Furthermore thanks to the nice Pivot Table Feature of LS, we have very pretty solution directly for the Monthly Overview as well:

![image](https://github.com/CorrelAidSwitzerland/a4d/assets/8046474/5c7d5ff2-04e1-46cf-a9a7-5dc08c8f552f)


As you can see, I had to use a second table for the calculation of yearly differences, because LS just can not calculate on filtered data (or give another nice approach to directly add a difference column to the pivot table).


For the table on the right side, I added a Query with Wide-Format December Totals per Year per clinic to BQ and merge it with the static data (which I uploaded manually via CSV to BQ with Clinic Codes matched with names and e.g. quotas based on Tylas` Excel):

`WITH
  TEMP AS (
  SELECT
    clinic_code,
    tracker_year,
    COUNT(*) AS active_patients
  FROM
    `a4d-315220.tracker.patient_data`
  WHERE
    status IN ("Active",
      "Active - Remote",
      "Query",
      "Inactive") AND tracker_month = 12
  GROUP BY
    country_code,
    clinic_code,
    tracker_year)
SELECT
  *
FROM
  TEMP PIVOT(SUM(active_patients) AS totals FOR tracker_year IN (2022,
      2021,
      2020))
Join  `a4d-315220.tracker.clinic_data_static` Using (clinic_code)`

I have overwritten a4d-315220.tracker.clinic_data_static_22 with the result of this query to get a "2022"-Version of the relevant clinic-data with end year totals, names, quota22 and so on...


Currently we have multiple things to solve:

- [ ]  Missing clinic data for the shown clinic codes
- [ ]  (Low Prio) Single Defined Quota for two clinics (Total Quota for both) (Province Yagon - we can not really support this)
- [ ] Implement Country Quota Table 
- [ ] Implement Quota 2023 
- [ ] Speak with Tyla about what she needs for the running year ( So imagine everything works: What does she expect to happen in January: Are all tracker files for 2023 are available right away or does she need a way to deal with incomplete data (especially having something like a Overview of what trackers have been analyzed, are expected or missing). This is a task that is normally implicitly done if you do everything by hand, but now it is automatic and there is no good way to know on what grounds the data was calculated. This "Implicits" need to be questioned.

**Comment by pmayd** [comment]
@lboel can we discuss/extract next steps into new issues and close this one asap?

**Comment by lboel** [comment]
Yes, I think we can just close this and open a new one at a later time.


"Close enough" is reached here and and next steps are depending on the new wishes for the  2023 data. 

I think things like insulin regimen column cleaning will enhance the report automatically.

I will open a ticket for streamline the clinic code and clinic name (static clinic data) ingesting.
