### ISSUE TITLE
Project structure cleanup

### ISSUE THREAD

**Issue by KonradUdoHannes** [CorrelAidSwitzerland/a4d#93]
I suggest the following steps to cleanup the project structure a little bit in order to facilitate easier documentation of the project wrt. to handover etc. An improved structure will also allow us to add additional small readmes to subfolders which is sometimes more helpful than a very long readme in project root.

## Reference data

Currently reference data is scattered a bit. Namely
- there are `synonyms` folder
- there are `provinces` folder
- there is a `master variable_tracker.xlsx`, which in itself has many tabs.
I suggest to create a `reference_data` folder and move all the above there. This will also make it easier to split up the `.xlsx` file into more machine readable formats, any extracted data file will naturally belong into the reference data folder.

## Scripts

There is a scripts folder, but it currently does not contain all the scripts. We have
- scripts in the scripts folder
- 5 scripts in the project root

I recommend to consolidate all these inside the scripts folder. I also suggest replacing the python script for log analysis with an R one to simplify the projects tech stack.

## Shiny

I suggest to delete it as it is currently not used.

**Comment by KonradUdoHannes** [comment]
@pmayd @tvolegtv any comments, additions etc. on this. Since you guys worked most with the code you should be happy with the suggestions before this issue leaves the backlog.

**Comment by KonradUdoHannes** [comment]
@pmayd Any further comments on this? Otherwise we can move it out of the backlog.

**Comment by pmayd** [comment]
Sorry was to occupied with other things but I agree with your points ,good suggestion so lets do it and move it to ready instead of backlog.

I would love to see all reference data in YAML format instead of any excel files and we only use a tiny fraction of the original master tracker file excel file if I remember correctly (not sure what you need from it)

The reason for the scripts in the scripts folder is that that is required by devtools and how R packages are structured. The main scripts are not function in a meaningful sense and cannot be seen as functions that we want to call, each main script is slightly different and does things differently. So I see no advantages from putting these in the R folder and I am not sure how devtools will handle these files (creating documentation etc). If you have a better understanding or still think this is necessary/beneficial, go for it, but for me it makes sense that all helper code is in the R folder and the main scripts are using anything that is inside.

AS for the Python script, it is merely for me to analyse the log files and I hope we find a better solution but for now it is completely optional and no one is using it so not sure if we have to replace it with an R version but that is up to the person taking care of the error report

**Comment by pmayd** [comment]
We should decide if we want to omit the shiny app as no one ever used/started it so in my opinion we can get rid of it

**Comment by pmayd** [comment]
But I agree that the root is already polluted or very noisy because of all the other project files so indeed it would be nice to have all the R code inside the R folder....we can use the somewhat strange convention to number files in their execution order and for the helper scripts I guess we could rename all to start with helper_ or something similar to make clear that they are not meant for being executed on their own.

**Comment by pmayd** [comment]
I think that's it for the structure, not much left we can change besides the scripts in the R folder, not sure if there are too many or if there is any benefit in putting the content differently, mainly less files or even more, smaller files. I tried this several times but the sheer numbers are overwhelming. But I guess we could somewhat streamline the naming and find a better way to group the files

**Comment by KonradUdoHannes** [comment]
Just to clarify my intention is to put the R scripts into the scripts folder, which itself is outside the R folder so I don't think it interferes with devtools, but we'll check anyways.
As for shiny (and generally all other things that are currently not used) I would always strongly suggest to just remove it. After all if we really end up needing it we can go back in the commit history and retrieve it. To make this easier in the event that such a case occurs we could add an annotated tag to the commit so it is more easily found in the commit history later on.

**Comment by pmayd** [comment]
A thanks I did not understand this correctly, then!

**Comment by pmayd** [comment]
yep I would also suggest using tags for this, great
